import { Product } from '../../../types/product';

export const mockProducts: Product[] = [
  {
    productId: 100,
    name: '아이폰 15 Pro',
    description: '최신 아이폰입니다.',
    price: 1500000,
    productCategory: {
      productCategoryId: 2,
      name: '스마트폰',
      parentCategoryId: 1,
      subCategories: [],
    },
    provider: {
      providerId: 10,
      name: 'Apple',
      description: '애플 공식 스토어',
    },
    options: [
      {
        id: 1,
        name: 'Color',
        value: 'Natural Titanium',
        quantity: 50,
        optionOrder: 1,
        sellPrice: 1500000,
      },
      {
        id: 2,
        name: 'Color',
        value: 'Blue Titanium',
        quantity: 30,
        optionOrder: 2,
        sellPrice: 1500000,
      },
      {
        id: 3,
        name: 'Storage',
        value: '256GB',
        quantity: 100,
        optionOrder: 3,
        sellPrice: 1500000,
      },
      {
        id: 4,
        name: 'Storage',
        value: '512GB',
        quantity: 50,
        optionOrder: 4,
        sellPrice: 1700000,
      },
    ],
    images: [
      {
        id: 1,
        url: '/images/iphone-natural.jpg',
        fileOrder: 1,
        isRepresentative: true,
      },
    ],
  },
  {
    productId: 101,
    name: '갤럭시 S23 Ultra',
    description: '최신 갤럭시입니다.',
    price: 1400000,
    productCategory: {
      productCategoryId: 2,
      name: '스마트폰',
      parentCategoryId: 1,
      subCategories: [],
    },
    provider: {
      providerId: 11,
      name: 'Samsung',
      description: '삼성전자 공식 스토어',
    },
    options: [
      {
        id: 5,
        name: 'Color',
        value: 'Phantom Black',
        quantity: 40,
        optionOrder: 1,
        sellPrice: 1400000,
      },
      {
        id: 6,
        name: 'Color',
        value: 'Cream',
        quantity: 35,
        optionOrder: 2,
        sellPrice: 1400000,
      },
      {
        id: 7,
        name: 'Storage',
        value: '256GB',
        quantity: 80,
        optionOrder: 3,
        sellPrice: 1400000,
      },
      {
        id: 8,
        name: 'Storage',
        value: '512GB',
        quantity: 40,
        optionOrder: 4,
        sellPrice: 1600000,
      },
    ],
    images: [
      {
        id: 2,
        url: '/images/galaxy-black.jpg',
        fileOrder: 1,
        isRepresentative: true,
      },
    ],
  },
  {
    productId: 102,
    name: 'MacBook Pro 16',
    description: '최신 맥북 프로입니다.',
    price: 3500000,
    productCategory: {
      productCategoryId: 3,
      name: '노트북',
      parentCategoryId: 1,
      subCategories: [],
    },
    provider: {
      providerId: 10,
      name: 'Apple',
      description: '애플 공식 스토어',
    },
    options: [
      {
        id: 9,
        name: 'Color',
        value: 'Space Gray',
        quantity: 20,
        optionOrder: 1,
        sellPrice: 3500000,
      },
      {
        id: 10,
        name: 'Color',
        value: 'Silver',
        quantity: 15,
        optionOrder: 2,
        sellPrice: 3500000,
      },
      {
        id: 11,
        name: 'Memory',
        value: '16GB',
        quantity: 30,
        optionOrder: 3,
        sellPrice: 3500000,
      },
      {
        id: 12,
        name: 'Memory',
        value: '32GB',
        quantity: 20,
        optionOrder: 4,
        sellPrice: 4000000,
      },
    ],
    images: [
      {
        id: 3,
        url: '/images/macbook-gray.jpg',
        fileOrder: 1,
        isRepresentative: true,
      },
    ],
  },
];
